services:
  conjakeions-plus:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: conjakeions-plus
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=America/New_York
    volumes:
      - puzzle-data:/app/data
    networks:
      - conjakeions-network


volumes:
  puzzle-data:
    driver: local
networks:
  conjakeions-network:
    driver: bridge
