services:
  conjakeions-plus:
    image: ghcr.io/slmingol/conjakeions-plus:latest
    container_name: conjakeions-plus
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - conjakeions-network
    volumes:
      - puzzle-data:/app/data

volumes:
  puzzle-data:
    driver: local

networks:
  conjakeions-network:
    driver: bridge
